#!/usr/bin/env python
import subprocess
import os
import sys

from honeypot import *

"""
This script restarts the Man-In-The-Middle (MITM) service
for any (or all) given honeypots. It kills the existing
process and replaces it with a new one.

Proper usage:
./mitm-restart <honeypot # | all>
"""

MITM_FILE = '/root/MITM/mitm/index.js'
MITM_LOG_PATH = '~/mitm_logs/mitm'
honeypots = []

def start_hp(hp_id):
    hp = None
    for hps in honeypots:
        if hps.hp_id == hp_id:
            hp = hps
            break
    if hp is None and hp_id != 'all':
        print('Failed to locate honeypot ' + hp_id + '.')
        exit()

    if hp_id == 'all':
        start_hp('1')
        start_hp('2')
        start_hp('3')
        start_hp('4')
    else:
        cmd_nh = 'nohup node %s HACS202_D %s %s %s > %s%s.log 2>&1&' % (MITM_FILE, hp.mitm_p, hp.c_ip, hp.c_id, MITM_LOG_PATH, hp.hp_id)

        os.system(cmd_nh)

def stop_hp(hp_id):
    hp = None
    for hps in honeypots:
        if hps.hp_id == hp_id:
            hp = hps
            break
    if hp is None and hp_id != 'all':
        print('Failed to locate honeypot ' + hp_id + '.')
        exit()

    if hp_id == 'all':
        stop_hp('1')
        stop_hp('2')
        stop_hp('3')
        stop_hp('4')
    else:
        cmd_ps = 'ps aux | grep mitm | grep %s | grep -v \'/bin/sh\' | awk \'{print $2}\'' % hp.c_id
        cmd_kl = 'kill '

        pid = subprocess.check_output(cmd_ps, shell=True, stderr=subprocess.STDOUT).strip()
        os.system(cmd_kl + pid)

def restart_hp(hp_id):
    hp = None
    for hps in honeypots:
        if hps.hp_id == hp_id:
            hp = hps
            break
    if hp is None and hp_id != 'all':
        print('Failed to locate honeypot ' + hp_id + '.')
        exit()

    if hp_id == 'all':
        restart_hp('1')
        restart_hp('2')
        restart_hp('3')
        restart_hp('4')
    else:
        cmd_ps = 'ps aux | grep mitm | grep %s | grep -v \'/bin/sh\' | awk \'{print $2}\'' % hp.c_id
        cmd_kl = 'kill '
        cmd_nh = 'nohup node %s HACS202_D %s %s %s > %s%s.log 2>&1&' % (MITM_FILE, hp.mitm_p, hp.c_ip, hp.c_id, MITM_LOG_PATH, hp.hp_id)

        pid = subprocess.check_output(cmd_ps, shell=True, stderr=subprocess.STDOUT).strip()
        os.system(cmd_kl + pid)
        os.system(cmd_nh)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Invalid number of arguments. Proper usage is ./mitm-restart <start|stop|restart> <honeypot #|all>')
    elif sys.argv[1] not in ['start', 'stop', 'restart'] or sys.argv[2] not in ['1', '2', '3', '4', 'all']:
        print('Invalid argument used. Proper usage is ./mitm-restart <start|stop|restart> <honeypot #|all>')
    else:
        honeypots = load_hpData()
        if sys.argv[1] == 'start':
            start_hp(sys.argv[2])
        elif sys.argv[1] == 'stop':
            stop_hp(sys.argv[2])
        else:
            restart_hp(sys.argv[2])
